### ISSUE TITLE
Export Search to Excel not working on Alfresco 6.1

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1902]
Appears to be caused by different/missing POI JAR(s).

Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Font.setBoldweight(S)V
        at com.tsgrp.opencontent.core.excel.ExcelUtil.buildWorkBook(ExcelUtil.java:111) ~[{client-module}.1.core-3.2.0.jar:3.2.0]

**Comment by henryerzinger** [comment]
Fixed with revision 22655
